substitutions:
  _IMAGE: europe-west10-docker.pkg.dev/gen-lang-client-0354690158/mlops02476-accident-images-eu-7f3a/app:latest
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/api/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
