steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/monitoring/Dockerfile
      - -t
      - europe-west10-docker.pkg.dev/gen-lang-client-0354690158/mlops02476-accident-images-eu-7f3a/drift-api:latest
      - .
images:
  - europe-west10-docker.pkg.dev/gen-lang-client-0354690158/mlops02476-accident-images-eu-7f3a/drift-api:latest
